[Table of Contents](table_of_contents.ipynb)

# Topic 24.  Singular Value Decomposition
Author: Brendon Forsgren (bforsgren29@gmail.com)
    

##  Introduction
Singualar Value Decomposition (SVD) is a matrix decomposition for any
complex matrix that results in 2 unitary matrix and a diagonal matrix of
singular values. SVD is a generalization of Eigenvalue Decomposition
and is valid for any complex matrix, not just square matrices.

SVD is one of the most important techniques of Linear Algebra 
(to the point that it could be called a power tool!) and for good reason.
The SVD provides a robust solution to Least Squares and Min-Norm problems.
Additionally it allows for a robust solution for ill conditioned problems
(problems where the condition number of the A matrix is very high).
Lastly, while many matrix decompositions have certain requirements about the matrix
being decomposed (LU: square and full rank, Cholesky: square, full rank, and
symetric positive definite, Eigenvalue Decomposition: Hermitian) SVD has no
such requirements.

## Explanation of the theory

As mentioned above, SVD is a generalization of the $A=S\Lambda S$ also known
as the Eigenvalue Decomposition. The SVD extends this 
to be the following decomposition for any complex $m\times n$ matrix:

\begin{align}
A = U\Sigma V^H
\end{align}

where $U \epsilon C^{m\times m}$ and unitary, $V \epsilon C^{n\times n}$
and unitary, and $\Sigma \epsilon R^{m \times n}$ and diagonal.
$\Sigma$ is also filled with Singular Values $\sigma_i$ such that 
$\sigma_1 >= \sigma_2 >= ... >= \sigma_p >= 0$ where p = min(m, n). $\Sigma$ is a rectangular
matrix and as a result $\Sigma$ is diagonal along the main diagonal with the
remaining rows or columns being fille with zeros as shown below.

\begin{align}
\Sigma = \begin{pmatrix} \sigma_1 & 0 & 0 & 0 \\ 0 & \sigma_2 & 0 & 0 \\ 0 & 0 & \sigma_3 & 0 \end{pmatrix}
or  \Sigma = \begin{pmatrix} \sigma_1 & 0 & 0 \\ 0 & \sigma_2 & 0 \\ 0 & 0 & \sigma_3 \\ 0 & 0 & 0 \end{pmatrix}
\end{align}


An interesting property of the singular values in $\Sigma$ is that they are the squareroot of the
eigenvalues of $A^HA$ and $AA^H$ or $\sigma_i = \sqrt{\lambda_i}$. This is shown by the following:
\begin{align}
A^HA = V\Sigma^H U^H U \Sigma V^H\\
A^HA = V\Sigma^H I \Sigma V^H\\
A^HA = V\Sigma^H \Sigma V^H\\
\end{align}
Let $\Sigma^H \Sigma = \Lambda$
\begin{align}
A^HA = V \Lambda V^H
\end{align}
Now multiplying each side on the right by V gives us
\begin{align}
A^HAV = V \Lambda
\end{align}
Which is the definition of an eigenvalue. Therefore the eigenvalues ($\Lambda$)
of $A^HA$ are the square of the singular values ($\Sigma$) of A.
The same process can be repeated with the matrix $AA^H$ to obtain the same result
Additionally it should be noted that in the case that A is a square matrix
The SVD of A becomes equivalent to the Eigenvalue Decomposition and $\sigma_i = \lambda_i$.

Often it is convenient to use the following block matrix structure to write the SVD.
\begin{align}
A = \begin{pmatrix} U_1 & U_2 \end{pmatrix} \begin{pmatrix} \Sigma_1 & 0 \\ 0 & \Sigma_2 \end{pmatrix} \begin{pmatrix} V_1^H \\ V_2^H \end{pmatrix}
\end{align}

Where $U_1 \epsilon C^{m\times r}$, $U_2 \epsilon C^{m \times (m-r)}$,
$V_1^H \epsilon C^{r \times n}$, $V_2^H \epsilon C^{(n-r) \times n}$,
$\Sigma_1 = diag(\sigma_1, ... , \sigma_r)$ of size $r\times r$ and
$\Sigma_2$ is a diagonal matrix of size $(m-r) \times (m-r)$ and $\sigma_i = 0$.
This allows A to be written in the following format in terms of the non-zero singular values.
\begin{align}
\\
A = U_1 \Sigma_1 V_1^H = \Sigma_{i=1}^r \sigma_i u_i v_i^H
\end{align}

This will be useful when finding solutions to equations in the form Ax=b when
A is rank deficient.

## Simple Numerical Examples

As mentioned above the SVD has numerous applications to solving the problem $Sx = b$.
In this section I will show some examples of how the matrix rank relates to the SVD,
how to find the pseudo-inverse of matrix A using the SVD, and how to solve poorly conditioned problems using SVD.


The first example deals with the rank of matrix A. Simply put the rank of A is
equal to the number of non-zeros singular values (the rank of $\Sigma$).
This can simply be shown using the following proof: 
\begin{align}
A = U \Sigma V^H\\
rank(A) = rank(U \Sigma V^H)\\
\end{align}
Since U and $V^H$ are unitary they do not affect the rank of $\Sigma$.Therefore 
\begin{align}
rank(A) = rank(\Sigma)
\end{align}
The following python codes illustrates this.

In [11]:
import numpy as np
import scipy.linalg as spl
import numpy.linalg as npl

def checkSingularValues(s):
    s[s<1e-10] = 0
    return s

# For a random matrix
A = np.random.randint(-10, 10, size=(4, 5))
U, s, Vh = spl.svd(A)
s = checkSingularValues(s)
print('A:', A)
print('The numer of non-zero singular values in A is:', np.count_nonzero(s))
print('The rank of A is:', npl.matrix_rank(A))

# For a rank deficient matrix
B = np.array([[2, 7, -7, 4, -15], [12, 2, -3, -17, 6], [4, 14, -14, 8, -30], [36, 6, -9, -51, 18], [1, 3.5, -3.5, 2, -7.5]])
U, s, Vh = spl.svd(B)
print('B:', B)
s = checkSingularValues(s)
print('The numer of non-zero singular values in B is:', np.count_nonzero(s))
print('The rank of B is:', npl.matrix_rank(B))


A: [[  7  -8   4   7  -7]
 [ -9   6  -4  -2   1]
 [  4   0   4   8 -10]
 [ -9  -6  -4   9   8]]
The numer of non-zero singular values in A is: 4
The rank of A is: 4
B: [[  2.    7.   -7.    4.  -15. ]
 [ 12.    2.   -3.  -17.    6. ]
 [  4.   14.  -14.    8.  -30. ]
 [ 36.    6.   -9.  -51.   18. ]
 [  1.    3.5  -3.5   2.   -7.5]]
The numer of non-zero singular values in B is: 2
The rank of B is: 2



The next example will show how to compute the pseudo inverse using SVD.
This can be done for both full rank and rank deficient matrices.
The following derivation shows how to find the pseudo inverse for a full rank, tall matrix.
\begin{align}
A = \begin{pmatrix} U_1 & U_2 \end{pmatrix} \begin{pmatrix} \Sigma_1 \\ 0 \end{pmatrix} V^H = U_1 \Sigma_1 V^H\\
(A^HA)^{-1}A^H = (V \Sigma_1 U_1^H U_1 \Sigma_1 V^H)^{-1}V \Sigma_1 U^H\\
(A^HA)^{-1}A^H = (V \Sigma_1 \Sigma_1 V^H)^{-1}V \Sigma_1 U^H\\
(A^HA)^{-1}A^H = V \Sigma_1^{-1} \Sigma_1^{-1} V^H V \Sigma_1 U^H\\
(A^HA)^{-1}A^H = V \Sigma_1^{-1} U^H\\
Where \Sigma_1^{-1} = diag(1/\sigma_1, 1/\sigma_2,..., 1/\sigma_r)
\end{align}
To extend this to a rank deficient matrix simply get rid of all the singular values equal to 0
and the columns in $U$ and rows in $V^H$ corresponding to those values.
The following code has and example finding the pseudo inverse for a tall matrix.


In [4]:
def invertSingularValues(s):
    index = np.nonzero(s)
    s[index] = 1.0/s[index]
    return s

# Tall matrix case
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [2, 6, 5]])
b = np.array([3, -5, 9, 10]).T
U, s, Vh = spl.svd(A)

s = checkSingularValues(s)
s = invertSingularValues(s)

S = np.diag(s)
S = np.hstack((S, np.zeros((3, 1))))
SVD_inv = Vh.T @ S @ U.T
x_svd = SVD_inv @ b

A_inv = npl.pinv(A)
x = A_inv @ b
print('x_svd:', x_svd)
print('x:', x)


x_svd: [-0.26666667  4.2        -2.93333333]
x: [-0.26666667  4.2        -2.93333333]


This example is for a fat matrix.


In [6]:
A = np.array([[1, 2, 3, 4], [5, 4, 3, 2], [-1, 6, -2, 3]])
b = np.array([2, 6, -3]).T
U, s, Vh = spl.svd(A)

s = checkSingularValues(s)
s = invertSingularValues(s)

S = np.diag(s)
S = np.vstack((S, np.zeros((1, 3))))
svd_inv = Vh.T @ S @ U.T
x_svd = svd_inv @ b

A_inv = npl.pinv(A)
x = A_inv @ b
print('x_svd:', x_svd)
print('x:', x)


x_svd: [ 0.94444444 -0.05555556  0.61111111 -0.16666667]
x: [ 0.94444444 -0.05555556  0.61111111 -0.16666667]


This example is for a rank deficient matrix.


In [10]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [2, 4, 6]])
r = npl.matrix_rank(A)
b = np.array([3, -5, 9, 10]).T
U, s, Vh = spl.svd(A)

s = checkSingularValues(s)

S = np.diag(s)
U1 = U[:, 0:r]
S1 = S[0:r, 0:r]
V1h = Vh[0:r, :]

print('U1*S1*V1h:', U1 @ S1 @ V1h)
S1 = npl.inv(S1)
svd_inv = V1h.T @ S1 @ U1.T
x_svd = svd_inv @ b

x = npl.pinv(A) @ b
print('x_svd:', x_svd)
print('x:', x)


U1*S1*V1h: [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]
 [2. 4. 6.]]
x_svd: [-1.67521368  0.04273504  1.76068376]
x: [-1.67521368  0.04273504  1.76068376]


## An Engineering Application

Provide a more sophisticated example showing one engineering example of the topic, complete with python code.